<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Page</name>
   <tag></tag>
   <elementGuidId>03d861de-d2a5-4f0a-aa11-0ba16ce263d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.article__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[11]/div[2]/div/div[4]/div[1]/div[1]/div/div/div[2]/div[1]/div/div[1]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>article__title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>В России за сутки госпитализировали 6211 человек с COVID-19</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endless&quot;)/div[@class=&quot;endless__item m-active&quot;]/div[@class=&quot;endless__item-content page__width&quot;]/div[@class=&quot;layout-article&quot;]/div[@class=&quot;layout-article__over&quot;]/div[@class=&quot;layout-article__main&quot;]/div[@class=&quot;article m-article m-ria&quot;]/div[@class=&quot;layout-article__600-align&quot;]/div[@class=&quot;article__header&quot;]/div[@class=&quot;article__title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='endless']/div/div/div/div[2]/div/div/div/div[2]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(обновлено: 12:31 23.01.2022)'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В России выявили 63 205 новых случаев заражения коронавирусом'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© РИА Новости / Илья Питалев'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div/div/div/div[2]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
