<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>News</name>
   <tag></tag>
   <elementGuidId>c9f4dce8-023d-4a18-8edd-3a5735580f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cell-list__item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[11]/div[2]/div/div[4]/div[2]/div[1]/div[1]/div[1]/div[5]/div/div/div/div/div[2]/div[2]/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-list__item-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Россия не будет терпеть провокации в Донбассе, заявил глава делегации в Вене </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;section__cell&quot;]/div[@class=&quot;section__content&quot;]/div[@class=&quot;floor&quot;]/div[@class=&quot;floor__cell&quot;]/div[@class=&quot;floor__cell-size&quot;]/div[@class=&quot;floor__cell-shape mod-shape-2x2&quot;]/div[@class=&quot;floor__cell-content&quot;]/div[@class=&quot;cell cell-list m-title&quot;]/div[@class=&quot;cell-list__list&quot;]/div[@class=&quot;cell-list__item m-no-image&quot;]/a[@class=&quot;cell-list__item-link color-font-hover-only&quot;]/span[@class=&quot;cell-list__item-desc&quot;]/span[@class=&quot;cell-list__item-title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div/div[5]/div/div/div/div/div[2]/div/a/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Главное'])[1]/following::span[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Российские биатлонисты завоевали серебро в эстафете на этапе Кубке мира'])[1]/following::span[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В России за сутки госпитализировали 6211 человек с COVID-19'])[1]/preceding::span[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Экс-депутат Рады Евгений Мураев: заявления МИД Британии — глупость, надеюсь на извинения'])[1]/preceding::span[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Россия не будет терпеть провокации в Донбассе, заявил глава делегации в Вене']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span/span</value>
   </webElementXpaths>
</WebElementEntity>
